@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDI3Nzc0MTV9.oDeJ6b9V9PMxFI6eEI_HqU56uJvYxKGTvQK76SrGqrs

### ao logar, gera um token que deve ser usado para acessar as rotas da API
curl -X 'POST' 'http://127.0.0.1:8000/token' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'username=abc&password=bolinhas'

### teste token
curl -X 'GET' 'http://127.0.0.1:8000/token/logado/' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer {{token}}'

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar um
GET http://localhost:8000/funcionario/2 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Vinicius Kunzler",
    "matricula": "lu12353",
    "cpf": "1334223449",
    "telefone": "tel2383738",
    "grupo": 1,
    "senha": "123456"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/4 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome" : "Vinicius Kunzlarrrrrrr", 
    "matricula" : "vini12353",
    "cpf" : "1334223449",
    "telefone" : "tel2383738", 
    "grupo" : 1,
    "senha" : "123456"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/4 HTTP/1.1
Authorization: Bearer {{token}}